# ─── tmux 配置 ───────────────────────────────────────────

# 开启鼠标支持 (允许用鼠标调整面板大小、点击切换窗口)
set -g mouse on

# 256 色支持
set -g default-terminal "screen-256color"

# 将前缀键修改为 Ctrl+a
set -g prefix C-a
# unbind C-b
# bind C-a send-prefix
